<?php
    include('models/db_conn.php');
    include('models/db_error.php');
    include('models/cat_model.php');
    include('models/product_model.php');
    include('models/user_model.php');
    include('models/cart_model.php');
    include('models/item_model.php');
    include('models/address_model.php');
?>